services:
  app:
    image: ruby:3.2.2
    command: sh -c "curl -sL https://deb.nodesource.com/setup_14.x | bash - && apt-get install -y nodejs && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports: 
      - "3000:3000"
    depends_on:
      - mysql
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      RAILS_ENV: development
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: sample_app
  mysql:
    image: mysql:8.0
    volumes:
      - sample-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: sample_app

volumes:
  sample-mysql-data: